name: CI

on:
  push:
  pull_request:

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: "`cargo fmt --all -- --check`"
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: "`cargo clippy -v -- -D warnings`"
        run: cargo clippy -v -- -D warnings

      - name: "`cargo test -v`"
        run: cargo test -v
